---
title: Tech stream
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Technology, Leadership, Engineering, Product, UX and more..
disqus_shortname: ''
comments: false
reading_time: true
words_per_minute: 100
url: "//udayakiran.github.io"
owner:
  name: Udaya Kiran
  avatar: uday.jpg
  bio: Engineering & Product Leader, Programmer, Entrepreneur
  email: udaykiran.vit@gmail.com
  twitter: 
  facebook: 
  github: udayakiran
  stackexchange: 
  linkedin: udaykirank
  instagram: 
  flickr: 
  tumblr: 
  google_plus: 
background: 
google_analytics: 
google_verify: 
bing_verify: 
future: true
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
include:
- ".htaccess"
exclude:
- "*.less"
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- config
- gulpfile.js
- lib
- log
- node_modules
- package.json
- spec
- tmp
- vendor
coderay:
  coderay_line_numbers: nil
  coderay_line_numbers_start: 1
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: class
